[package]
name = "elemeld"
version = "0.1.0"
authors = ["MetaDark <kurt.bruneau@gmail.com>"]

[dependencies]
mio = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
x11-dl = "*"
dylib = "*"
libc = "*"
nix = "*"
log = "*"
env_logger = "*"
